-- Creación de tabla para Eventos del Calendario
-- Permite guardar hora exacta (timestamp) y ubicación (lat/long)

CREATE TABLE public.eventos (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_usuario integer NOT NULL,
  titulo text NOT NULL,
  tipo text NOT NULL, -- Ej: 'Reunión', 'Trabajo', 'Cita', 'Otro'
  fecha_inicio timestamp with time zone NOT NULL,
  fecha_fin timestamp with time zone NOT NULL,
  latitud double precision,
  longitud double precision,
  ubicacion_nombre text,
  created_at timestamp with time zone DEFAULT now(),
  
  CONSTRAINT eventos_pkey PRIMARY KEY (id),
  CONSTRAINT eventos_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuario(id) ON DELETE CASCADE
);

-- Índices para mejorar rendimiento de consultas por usuario y fecha
CREATE INDEX idx_eventos_usuario ON public.eventos(id_usuario);
CREATE INDEX idx_eventos_fechas ON public.eventos(fecha_inicio);

-- Habilitar RLS (Row Level Security) - Opcional pero recomendado
ALTER TABLE public.eventos ENABLE ROW LEVEL SECURITY;

-- Política: Los usuarios solo pueden ver/editar sus propios eventos
CREATE POLICY "Usuarios ven sus propios eventos" ON public.eventos
  FOR ALL
  USING (id_usuario = (select id from public.usuario where auth_user_id = auth.uid()));
